language: node_js
node_js:
  - 'node' # Latest stable Node.js release
before_install: cd src
before_script:
  - npm install -g grunt
  - npm install -g grunt-cli
  - npm install
script:
  - npm run test
  - npm run build

